#!/usr/bin/env node
/*
 * Kahani Korner — self-host the Google Fonts the site uses.
 *
 *   node tools/google-fonts.mjs           # download fonts + write the CSS
 *   node tools/google-fonts.mjs --check   # exit 1 if Google now serves something
 *                                         # different from the self-hosted copy
 *
 * Fetches the exact stylesheet Google serves to current browsers for FAMILIES_URL
 * (Chrome and Safari receive the same CSS), downloads every font file it
 * references, and writes:
 *   assets/fonts/google/<family>-<subset>.<hash>.woff2
 *   assets/css/google-fonts.css   (same @font-face rules, same unicode-range
 *                                  subsets and font-display, local URLs)
 *
 * Safeguards: never edits HTML; font filenames carry a content hash, so an
 * existing file is never overwritten with different content; refuses to run
 * if Google returns anything but woff2 files from fonts.gstatic.com.
 *
 * Grandstander and Open Sans are licensed under the SIL Open Font License 1.1,
 * which allows self-hosting.
 */
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const FAMILIES_URL =
  "https://fonts.googleapis.com/css2?family=Grandstander:wght@700;800&family=Open+Sans:wght@400;600;700&display=swap";
const USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT_FONTS = path.join(ROOT, "assets/fonts/google");
const OUT_CSS = path.join(ROOT, "assets/css/google-fonts.css");
const CHECK = process.argv.includes("--check");

const die = (msg) => { console.error(`error: ${msg}`); process.exit(1); };
const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "");

if (!fs.existsSync(path.join(ROOT, "firebase.json"))) die(`not the site root: ${ROOT}`);

const res = await fetch(FAMILIES_URL, { headers: { "User-Agent": USER_AGENT } });
if (!res.ok) die(`Google Fonts returned ${res.status}`);
const css = await res.text();

// Every face: "/* subset */ @font-face { family, ..., src: url(...) format('woff2'); ... }"
const faces = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)];
const allUrls = [...css.matchAll(/url\(([^)]+)\)/g)].map((m) => m[1]);
if (!faces.length || faces.length !== (css.match(/@font-face/g) || []).length) die("unexpected stylesheet format from Google Fonts");
for (const u of allUrls) {
  if (!/^https:\/\/fonts\.gstatic\.com\/.+\.woff2$/.test(u)) die(`unexpected font URL: ${u}`);
}

// One local file per distinct remote file (variable fonts serve several weights).
const local = new Map(); // remote url -> { name, buf }
for (const [, subset, body] of faces) {
  const url = body.match(/url\(([^)]+)\)/)[1];
  if (local.has(url)) continue;
  const family = slug(body.match(/font-family:\s*'([^']+)'/)[1]);
  const r = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
  if (!r.ok) die(`download failed (${r.status}): ${url}`);
  const buf = Buffer.from(await r.arrayBuffer());
  if (buf.subarray(0, 4).toString("latin1") !== "wOF2") die(`not a woff2 file: ${url}`);
  local.set(url, { name: `${family}-${subset}.${sha256(buf).slice(0, 8)}.woff2`, buf });
}

let out = css;
for (const [url, { name }] of local) out = out.split(`url(${url})`).join(`url(/assets/fonts/google/${name})`);
out = `/* Self-hosted copy of ${FAMILIES_URL}
   Generated by tools/google-fonts.mjs — do not edit by hand.
   Grandstander and Open Sans: SIL Open Font License 1.1. */
${out}`;

const stale = [...local.values()].filter(({ name }) => !fs.existsSync(path.join(OUT_FONTS, name))).map(({ name }) => `assets/fonts/google/${name}`);
const current = fs.existsSync(OUT_CSS) ? fs.readFileSync(OUT_CSS, "utf8") : "";
if (current !== out) stale.push("assets/css/google-fonts.css");

console.log(`${faces.length} @font-face rules, ${local.size} font files`);
for (const { name, buf } of local.values()) console.log(`  ${name.padEnd(44)} ${buf.length} B`);

if (CHECK) {
  if (stale.length) { console.log(`OUT OF DATE: ${stale.join(", ")} — run node tools/google-fonts.mjs`); process.exit(1); }
  console.log("self-hosted fonts are up to date");
  process.exit(0);
}

fs.mkdirSync(OUT_FONTS, { recursive: true });
for (const { name, buf } of local.values()) {
  const dest = path.join(OUT_FONTS, name);
  if (fs.existsSync(dest)) {
    if (sha256(fs.readFileSync(dest)) !== sha256(buf)) die(`${name} exists with different content — not overwriting`);
  } else {
    fs.writeFileSync(dest, buf);
  }
}
if (current !== out) fs.writeFileSync(OUT_CSS, out);
console.log(stale.length ? `wrote: ${stale.join(", ")}` : "already up to date — nothing written");
const unused = fs.readdirSync(OUT_FONTS).filter((n) => ![...local.values()].some((v) => v.name === n));
if (unused.length) console.log(`older font files no longer referenced (safe to delete once deployed): ${unused.join(", ")}`);
